### PR TITLE
Fixes #6 - Added functionality: Prompts user between benchmark runs 

### LINKED ISSUE #6: Add 'PressAnyKeyToContinue' prompts
Add the option to prompt user confirmation in between benchmark runs.
Add a switch variable in the configuration section.

### PR DESCRIPTION
**Pull request by colinchaput**

### CODE REVIEW

**Comment by hdrie** [comment]
Hi, thanks for picking this up :)
Can you also create a bool variable in the config section to turn the prompting on and off? 

The input query could be a bit more forgiving. I would suggest defaulting to True and only aborting when [nN] is given.

**Comment by colinchaput** [comment]
No problem!

I like it. Let me see what I can do.

**Comment by colinchaput** [comment]
New PR submitted

**Comment by colinchaput** [comment]
Submitted PR #13

**Pull request closed without merging**
